config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :categories
 
  
  resources :articles do
    resources :comments
  end

  resources :comments do
    resources :comments
  end


  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.admin?
       can :manage,:all
    elsif user.client?
    can :show, Article
    can :manage,Comment
    else
       can :show, Article
    end

  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments, as: :commentable
    has_attached_file :image, :styles => { medium: "750x300", thumb: "200x200>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/,:message =>'--- incorrect file type  ---'
    validates_attachment_size :image,:in => 0..850.kilobytes,:message=>'--- file size it too big  ---'


end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :articles, dependent: :destroy
    has_many :comments, dependent: :destroy

   def admin?
    has_role?(:admin)
  end
   
  def client?
    has_role?(:client)
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
  

  protected
 

 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    load_and_authorize_resource
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [ :show]


    def show

    end
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
        @counter = Article.count + 1
        @categories =  Category.all
        if !params[:id].blank? 
            @article.category =  Category.find(params[:id])
        end
     end

     def edit
        @counter    =  Article.count 
        @categories =  Category.all
     end

     def destroy
        @article.destroy
           respond_to do |format|
           format.html { redirect_to ({:action=>"index"}), notice: 'Article was successfully destroyed.' }
           format.json { head :no_content }
        end
     end


     def update
        respond_to do |format|
            if @article.update(article_param)
               format.html { redirect_to ({:action=>"index"}), notice: 'Article was successfully updated.' }
               format.json { render :show, status: :ok, location:    @article}
            else
               format.html { render :edit }
               format.json { render json:  @article.errors, status: :unprocessable_entity }
            end
         end
     end

     def create 
        @article = Article.new(article_param)
        @article.user = current_user
        respond_to do |format|
         if @article.save
            format.html { redirect_to ({:action=>"index"}), notice: 'Article was successfully created.' }
            format.json { render :index, status: :created, location: @article }
         else
            format.html { render :new }
            format.json { render json: @article.errors, status: :unprocessable_entity }
         end
        end
     end


     private


     def article_param
        params.require(:article).permit(:name,:category_id,:visible,:content,:image)
     end

     def set_article
        @article = Article.find(params[:id])
     end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
        @counter = Category.count + 1
     end
    
     def edit
        @counter = Category.count
     end
 
     def create
        
        @Category = Category.new(category_params)
        
        respond_to do |format|
           if @Category.save
              format.html { redirect_to ({:action=>"index"}), notice: 'Category was successfully created.' }
              format.json { render :index, status: :created, location: @Category }
           else
              format.html { render :new }
              format.json { render json: @Category.errors, status: :unprocessable_entity }
           end
        end
     end

     def update
        respond_to do |format|
           if @category.update(category_params)
              format.html { redirect_to ({:action=>"index"}), notice: 'Recipe was successfully updated.' }
              format.json { render :show, status: :ok, location: @category }
           else
              format.html { render :edit }
              format.json { render json: @category.errors, status: :unprocessable_entity }
           end
        end
        
     end

     def destroy
        @category.destroy
           respond_to do |format|
           format.html { redirect_to ({:action=>"index"}), notice: 'Category was successfully destroyed.' }
           format.json { head :no_content }
        end
     end


private

def category_params
    params.require(:category).permit(:name, :visible,:lp)
end   

 def set_category
    @category = Category.find(params[:id])
 end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable
    before_action :authenticate_user!

    def index
      redirect_back fallback_location: root_path
    end

    def new
      @comment = Comment.new
      respond_to do |format|
        format.js { render action: "new" }
    end
    end

    def create
      @comment = @commentable.comments.new comment_params
      @comment.user = current_user
      if @comment.save
        redirect_back fallback_location: root_path  , notice: 'Your comment was successfully posted!'
      else
        redirect_back fallback_location: root_path , notice: "Your comment wasn't posted!"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Article.find_by_id(params[:article_id]) if params[:article_id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      @articles = Article.all
      @categories = Category.first(5)
    if !params[:category_id].blank? 
      @articles = Article.where("category_id in (?)", params[:category_id])
    end
    @articles  = @articles.paginate(:page => params[:page], :per_page => 5) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def errors_helper(object)
        render(:partial=>'additional/errors',:locals=>{:object=>object})
    end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/additional/_errors.html.erb
<% if object  && object.errors.size >0 %>


<dib class="bg-danger">
<table class="table">
    <tr class="danger">
            <td> Errors occurred while writing the record to the database, the number of errors <%= object.errors.size %>
            <br>
             for the following fields:</td>
            </tr>
         <% object.errors.full_mesasages.each do |message| %>
         <tr class="warning">
             <td><b> <%= message %> </b></td>
         </tr>
         <% end %>
</table>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

<%  errors_helper(@article) %>




<%  !if @article.image.file?  %>
<div class="form-group row">
    <%= f.label(:image,"Current Image",:class=> "col-sm-2 col-form-label") %><br />
    <div class="col-sm-10">
        <%= image_tag(@article.image.url(:thumb), :class=>"form-control")  %>
    </div>
  </div>
<% end %>

<div class="form-group row">
     <%= f.label(:image,"Header Image",:class=> "col-sm-2 col-form-label") %><br />
  <div class="col-sm-10">
      <%= f.file_field :image , :class=>"form-control"  %>
  </div>
</div>

  <div class="form-group row">
        <%= f.label :name,"Article Name",:class=> "col-sm-2 col-form-label" %><br />
        <div class="col-sm-10">
                <%= f.text_field :name , :class=>"form-control" %>
        </div>
   </div>

      <div class="form-group row">
            <%= f.label :visible,"Visibility",:class=> "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-10">
          <div class="form-check">
            <%= f.check_box :visible , :class=>"form-check-input" %>
          </div>
        </div>
      </div>

       <div class="form-group row">
            <%= f.label :category_id,"Category",:class=> "col-sm-2 col-form-label" %><br/>
                    <div class="col-sm-10">
                    <%= f.select :category_id,@categories.map{|t| [t.name,t.id]},{},{:class=>"form-control"} %>
                </div>
       </div>

    <div class="form-group row">
        <%= f.label :content,"Content",:class=> "col-sm-2 col-form-label" %><br />
        <div class="col-sm-10">
                <%= f.trix_editor :content %>
        </div>
   </div>
     
     
      <div class="form-group row">
        <div class="col-sm-10">
         <%= f.submit :class=>"btn btn-primary" %>
        </div>
      </div>


<% end %>

app/views/articles/edit.html.erb
<%= render partial: "form" %>

app/views/articles/index.html.erb
<div style="padding-bottom: 10px;">
        <%= link_to "Add new article", {:action=>'new'}, :class =>'btn btn-mini btn-primary' %>
        </div>
        
        <table class="table table-striped">
        <tr class="info">
                        <th>Name</th>
                        <th>Category</th>
                        <th>Added by</th>
                        <th>Visibility</th>
                        <th>Action</th>
        </tr>
        <% @articles.each do |article| %>
        <tr>
        <td><%= article.name %></td>
        <td><%= article.category.name %></td>
        <td><%= article.user.username %></td>
        <td><%= article.visible %></td>
        <td class="actions"> 
                <%= link_to("Edit",{:action=>'edit', :id => article.id }, :class =>'btn btn-xs btn-primary') %>
                <%= link_to("Remove",{:action=>'destroy',:id=>article.id }  , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger") %>
        </td>
        </tr>
        <% end %>
        </table>

app/views/articles/new.html.erb
<%= render partial: "form" %>

app/views/articles/show.html.erb
     <!-- Blog Post -->
     <div class="card mb-4">

        <% !if @article.image.file? %>
        <%= image_tag(@article.image.url(:medium), :class=>"card-img-top")  %>
        <% else %>
        <% end %>
      
        <div class="card-body">
          <h2 class="card-title"> <%= @article.name %> </h2>
          <p class="card-text"><%= @article.content.html_safe %></p>
        </div>
        <div class="card-footer text-muted">
          Posted on <%= @article.created_at %>
        </div>
      </div>
      
      <h3>Comments</h3>


      <% if user_signed_in? %>

<%= form_for [@article, Comment.new] do |f| %>
<%= f.text_area :content,:class=>"form-control", placeholder: "Add a comment" %><br/>
<%= f.submit "Add Comment", :class=>"btn btn-primary" %>
<% end %>

<%  end %>

<div class="comments">
<%= render(partial: 'comments/comment', collection: @article.comments) %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group row">
        <%= f.label :name,"Category Name",:class=> "col-sm-2 col-form-label" %><br />
        <div class="col-sm-10">
                <%= f.text_field :name , :class=>"form-control" %>
        </div>
   </div>
      <div class="form-group row">
            <%= f.label :visible,"Visibility",:class=> "col-sm-2 col-form-label" %><br/>
        <div class="col-sm-10">
          <div class="form-check">
            <%= f.check_box :visible , :class=>"form-check-input" %>
          </div>
        </div>
      </div>

      <div class="form-group row">
            <%= f.label :visible,"Display Index",:class=> "col-sm-2 col-form-label" %><br/>
                    <div class="col-sm-10">
                    <%= f.select :lp,1..@counter,{},{:class=>"form-control"} %>
                </div>
       </div>

     
      <div class="form-group row">
        <div class="col-sm-10">
         <%= f.submit :class=>"btn btn-primary" %>
        </div>
      </div>


<% end %>

app/views/categories/edit.html.erb
<%= render partial: "form" %>

app/views/categories/index.html.erb
<div style="padding-bottom: 10px;">
<%= link_to "Add new category", {:action=>'new'}, :class =>'btn btn-mini btn-primary' %>
</div>

<table class="table table-striped">
<tr class="info">
                <th>Display Index</th>
                <th>Name</th>
                <th>Visibility</th>
                <th>Action</th>
</tr>
<% @categories.each do |category| %>
<tr>
<td><%= category.lp %></td>
<td><%= category.name %></td>
<td><%= category.visible %></td>
<td class="actions"> 
        <%= link_to("Edit",{:action=>'edit', :id => category.id }, :class =>'btn btn-xs btn-primary') %>
        <%= link_to("Add article",{:controller=>'/articles',:action=>'new',:id=>category.id } , data: { confirm: 'Are you sure?' }, class: "btn btn-success") %>
        <%= link_to("Remove",{:action=>'destroy',:id=>category.id }  , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger") %>
</td>
</tr>
<% end %>
</table>

app/views/categories/new.html.erb
<%= render partial: "form" %>

   
   

app/views/comments/_comment.html.erb
    <div id="comment-<%= comment.id %>" class="rounded comments-group border border-primary" style="margin-top:10px;">
            <div class="comment-content col-md-11 col-sm-10">
                    <h6 class="small comment-meta"><a href="#"> <%=comment.user.username %> </a> <%= time_ago_in_words(comment.created_at) %> ago</h6>
                    <div class="comment-body">
                        <p>
                                <%=comment.content %>
                            <br>
                            <% if user_signed_in? %>
                             <%= link_to "Reply",   new_comment_comment_url(comment, js: true),:class=>"text-right small", :remote => true %>
                            <%  end %>
                        </p>
                    </div>

                </div> 
            </div>
            <ul>
                    <%= render partial: 'comments/comment', collection: comment.comments %>
            </ul>
   
    

app/views/comments/_reply.html.erb
<%= form_for [@commentable, Comment.new], :html=>{:id=>"new_comment_reply"} do |f| %>
<%= f.text_area :content, placeholder: "Add a Reply",:class=>"form-control" %><br/>
<%= f.submit "Reply" , :class=>"btn btn-primary" %>
<% end %>

app/views/comments/new.js.erb
$('#new_comment_reply').remove()

if($("#comment-<%=@commentable.id %>").children('#new_comment_reply').length==0){
$("#comment-<%=@commentable.id %>").append("<%= j render :partial => 'reply' %>");
}

app/views/home/_side.html.erb
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">


        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <% @categories.each do |category| %>
                  <li>
                      <%= link_to category.name,{ controller: "/home", action: "index",:category_id=>category.id } %>
                  </li>
                  <% end %>
              
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                      <%= link_to "ALL",{ controller: "/home", action: "index" } %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget 
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>
-->
      </div>

app/views/home/index.html.erb
  <!-- Page Content -->

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <% @articles.each do |article| %>

         <!-- Blog Post -->
         <div class="card mb-4">

          <% !if article.image.file? %>
          <%= image_tag(article.image.url(:medium), :class=>"card-img-top")  %>
          <% else %>
          <% end %>
        
          <div class="card-body">
            <h2 class="card-title"> <%= article.name %> </h2>
            <p class="card-text"><%= truncate(strip_tags(article.content.html_safe),:length=>200) %></p>
            <%= link_to "Read More",{ controller: "/articles", action: "show",:id=>article.id },:class=>"btn btn-primary" %>
          </div>
          <div class="card-footer text-muted">
            Posted on <%= article.created_at %>
          </div>
        </div>
        
        <% end %>

        <div class="text-center">
        <%= will_paginate @articles %>
      </div>

      </div>


 

<%= render  "side" %>

    </div>
    <!-- /.row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="vieport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>

  <!-- navigation bar -->
  <%= render  "shared/header" %>

  <!-- alerts  -->
  <%= render  "shared/alerts" %>
      
  <!-- content  -->
  <div class="container">
    <%= yield %>
  </div>

  <!-- footer  -->
  <%= render  "shared/footer" %>

  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
<p class="alert alert-info"> <%= notice %></p>
<% end %>

<% if alert %>
<p class="alert alert-danger"> <%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
    <!-- Footer    -->
    <footer class="py-5 bg-dark " style="margin-top: 20px;">
            <div class="container">
              <p class="m-0 text-center text-white">Copyright &copy; Paweł Lewandowski 2018 </p>
            </div>
         
          </footer>

app/views/shared/_header.html.erb
     <!-- Navigation -->
     <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h5 class="my-0 mr-md-auto font-weight-normal"></h5>
            <nav class="my-2 my-md-0 mr-md-3">
              <%= link_to "Home", root_path,:class=>"p-2 text-dark" %>
            </nav>
            
       
            <% if user_signed_in? %>
            <nav class="my-2 my-md-0 mr-md-3">
            <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Edit profile", edit_user_registration_path,:class=>"dropdown-item" %>
                  <% if current_user.admin? %>
                  <%= link_to "Categories",{ controller: "/categories", action: "index" },:class=>"dropdown-item" %>
                  <%= link_to "Articles",{ controller: "/articles", action: "index" },:class=>"dropdown-item" %>
                  <% end %>
                </div>
              </div>

          </nav>
          <% else %>
            <%= link_to "Log In", new_user_session_path,:class=>"btn btn-outline-primary"  %>
          <% end %>
          <% if user_signed_in? %>
           <%= link_to "Log Out", destroy_user_session_path, method: :delete,:class=>"btn btn-outline-danger" %>
          <% end %>

          </div>